### ISSUE TITLE
Fake Fullscreen patch misbehaving with chromium.

### ISSUE THREAD

**Issue by MaxTendency** [paniash/dwm#1]
I found your git while looking for a proper fakefullscreen toggle and your "fullscreen compilation" patch seems to be working well with mpv, firefox and a few other apps. 

However on chromium, it misbehaves. So if I toggle fake fullscreen on and then turn fullscreen on (in chrome) it goes offscreen. Basically its showing a zoomed in version. 

A workaround I found is to toggle (in app) fullscreen first and then toggle fake fullscreen. But the problem with this is it goes back to the misbehaving state after turning fullscreeen (in app) off and on. 

Anyclue on why this is happening or what I can do to fix this? I also installed your full dwm build (instead of just the patch) just to make sure I wasn't missing anything and chromium still misbehaves there as well.

**Comment by paniash** [comment]
@MaxTendency Hi! Apologies for the tardiness. 

Looks like this is a chromium specific issue and has nothing to do with dwm per se. However, I'll let you investigate and let me know if anything comes up, which we could add to the README. 

(Chrome does behave weirdly at times. For example, there's this issue on chromium which affects pulseaudio output and which really isn't a pulseaudio bug).
