### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by ghost** [paniash/dwm#2]
Hi Paniash.

This is going to sound nooby (because I'm a noob) but what does XK before each shortcut mean? I've been trying to use dwm and arch linux and couldn't figure out the shortcuts or how to open anything.

Sorry for being so inexperienced.

Thanks.

**Comment by paniash** [comment]
Hi @henrrr!

XK generally refers to the keybindings used in dwm and I think it has to do with [XKeyboard](https://www.freedesktop.org/wiki/Software/XKeyboardConfig/). Hope this helps. :-)
